services:
  - type: web
    name: mv-proshoot-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://muninaikjatoth_db_user:1OFtiMEYsJMOwcEL@cluster0.ppctehe.mongodb.net/mvproshoot?retryWrites=true&w=majority
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 7d
